### PR TITLE
translate site_title in email notifications

### PR DESCRIPTION
**Pull request by fanjinfei**
Fixes #

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [X ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
newer versions of ckan use a template for notification emails so this change won't be necessary. Maybe it's time to move to 2.6.

**Comment by fanjinfei** [comment]
close it as 2.6 already has fix

**Comment by thriuin** [comment]
@wardi I don't think we're planning to move 2.6 just yet - what timeline were you thinking of for this?

**Comment by wardi** [comment]
I won't have time until after PCO, but as soon as we can it would be good to do a proper test of our code against 2.6

**Comment by thriuin** [comment]
OK, so we'll try to make it a priority for early in the new fiscal year. I'll try to convince TBS to hold off until then for the e-mail password reset changes.

**Pull request closed without merging**
