### PR TITLE
fix dataset ATOM feed

### PR DESCRIPTION
**Pull request by fanjinfei**
Fixes #

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by wardi** [comment]
looks like this should be submitted to core

**Comment by fanjinfei** [comment]
Our branch is diverted from core. https://github.com/ckan/ckan/pull/3485 is not merged yet.

**Comment by wardi** [comment]
@fanjinfei you can make a PR that includes the ckan#3485 commits (or submit it against the branch in the PR if @TkTech prefers)

**Comment by fanjinfei** [comment]
I tried with https://github.com/ckan/ckan/pull/3609. need to fix tests, pagination, etc.

**Comment by wardi** [comment]
@fanjinfei you closed that PR, are you going to get @TkTech to merge it into his branch instead?

**Comment by fanjinfei** [comment]
I will submit a PR to @TkTech 's branch.

**Pull request closed without merging**
