### PR TITLE
Release v2.4 ndm

### PR DESCRIPTION
**Pull request by marcfor**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
I am fixing this in ckan master and will be porting it back when I am done

**Comment by marcfor** [comment]
OK great Laurent.  In the meantime, we're getting a failure when the variable "root" is not defined.  I'd like to define it as an empty string as the first line in the function as a fix while you're working on a more general fix.

**Comment by LaurentGoderre** [comment]
https://github.com/ckan/ckan/pull/2968

**Comment by LaurentGoderre** [comment]
Touching this function has a lot of potential side-effect. Fixing it in CKAN core allow us to leverage the unit tests

**Pull request closed without merging**
