### PR TITLE
Add notes to README on why this fork exists (and changelog?)

### PR DESCRIPTION
**Pull request by patcon**
This is just a stub for a format that would have been helpful when I was trying to understand and evaluate :) If you ok with the premise, feel free to toss it and start fresh.

### CODE REVIEW

**Comment by TkTech** [comment]
@patcon heyo. This fork should never be used, and exists solely for our internal use. We frequently needs features, fixes or dirty hacks before they can make it through the ckan release process and thus those changes live here.

**Comment by patcon** [comment]
Cool. Thanks! For what it's worth, people interested in working within GoC might hope to understand the natural give-and-take that happens internally with these things. Anyhow, just something to integrate into considerations if you ever consider documenting the fork going forward :)

**Comment by patcon** [comment]
And fwiw, writing what you just said in  the README ("This fork should never be used, and exists solely for our internal use. We frequently need features, fixes or dirty hacks before they can make it through the ckan release process") is exactly the sort of thing that would satisfy the curious of future curious folk!

**Comment by wardi** [comment]
@patcon I've just update the github description along those lines, how's that?

**Pull request closed without merging**
