### PR TITLE
Updated PO's

### PR DESCRIPTION
**Pull request by JVickery-TBS**
feat(i18n): extracted messages and updated catalogs;

- Extracted messages to POT.
- Updated en and fr POs.

### CODE REVIEW

**Comment by wardi** [comment]
for this repo we're better off not updating pot/po files to avoid major merge conflicts when upgrading. Since there are only a few new strings let's add them to ckanext-canada for now and try to remember to remove them when we upgrade if our translations are the same as the ones upstream.

**Comment by JVickery-TBS** [comment]
@wardi that sounds good. I will add them to the `strings.py` in `ckanext-canada` and then extract messages again.

This was going to be one of my questions: `gettext` only uses MO files right? So if we are deleting the generated French MO file in `ckan/ckan` in our deployments, are we even getting French translations from this repo on our servers?

**Comment by JVickery-TBS** [comment]
@wardi I guess so? But not sure where that is done exactly?

Before I changed the deploy script to not use the `build-combined-ckan-mo.sh`, it would run the script ([build-combined-ckan-mo.sh](https://github.com/open-data/ckanext-canada/blob/master/bin/build-combined-ckan-mo.sh))

In that script it runs:
```
python setup.py compile_catalog -f -d ../ckan/ckan/i18n --domain ckan --locale fr
```
Building the French MO file for `ckan/ckan`.

But then after that it removes the built MO file:
```
rm -r ckan/ckan/i18n/fr/LC_MESSAGES/ckan.mo
```

So I am not sure where it then gets rebuilt on the server after that?

**Comment by wardi** [comment]
oh, good question. surely the translations in our extension don't cover all the translations from core too, right?

**Comment by JVickery-TBS** [comment]
They don't. But the MO file for `ckan/ckan/i18n/fr` exists on the servers. So not sure how it gets there when we are deleting it in the last steps of deployment.

**Comment by JVickery-TBS** [comment]
Added custom strings or new strings from our fork into the `strings.py` script of the Canada extension. And I also copied two fuzzies from the French PO over to the Canada extension to get those fully translated as well.

Closing this one.

**Pull request closed without merging**
